# Spring Configuration
spring:
   application:
      name: jblog
   devtools:
      livereload:
         enabled: true
   mvc:
      # URL Resource Mapping
      static-path-pattern: /assets/**
      throw-exception-if-no-handler-found: true
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp
   web:
    resources:
       static-locations: classpath:/assets/, file:/jblog-uploads/
   # Multipart Resolver
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 50MB
   # MessageSource
   messages:
      always-message-format: true
      basename: web/messages/messages_ko
      encoding: utf-8
   aop:
      auto: true
      proxy0target-class: true
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://192.168.10.123:3307/jblog?charset=utf8
      username: jblog
      password: jblog
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20
# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml
# server
server:
   port: 9090
   servlet:
      context-path: /jblog06
      encoding:
         charset: utf-8
         enabled: true
         
#logging
logging:
   pattern:
      file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{5} - %msg%n"
   logback:
      rollingpolicy:
         file-name-pattern: /${spring.application.name}-logs/exception.%i.log.zip
         max-file-size: 200MB
         max-history: 10
      file: /${spring.application.name}-logs/exception.log
      level:
         root: warn
         com:
            douzone:
               jblog:
                  exception: ERROR